version: "2"

services:
  hybrid:
    # image: "cornfeedhobo/ircd-hybrid"
    build: .
    ports:
      - "6665:6665"
      - "6666:6666"
      - "6667:6667"
      - "6668:6668"
      - "6669:6669"
    volumes:
      - "./home/ircd/etc:/home/ircd/etc"
      - "./home/ircd/var:/home/ircd/var"
